# Generated by Django 2.0 on 2018-04-12 02:28

from django.db import migrations, models
import django.db.models.deletion
import toolkit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientPortal', '0002_auto_20180411_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('identify', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('diagnose_and_treat', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('refer', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('reinforce_and_teach', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('recommend', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('reduce_high_risk_behavior', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('be_culturally_attuned', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('prescribe', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('close_and_schedule', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('prevent_burnout', models.BooleanField(default=toolkit.models.Toolkit.answer_default)),
                ('docpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.DocPat')),
            ],
        ),
    ]
