# Generated by Django 2.0.6 on 2018-09-15 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientPortal', '0002_auto_20180915_1112'),
        ('toolkit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torturehistory',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torturehistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Patient'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='docpat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.DocPat'),
        ),
        migrations.AddField(
            model_name='htq',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='htq',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Patient'),
        ),
        migrations.AddField(
            model_name='hopkinspart2',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hopkinspart2',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Patient'),
        ),
        migrations.AddField(
            model_name='hopkinspart1',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hopkinspart1',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Patient'),
        ),
        migrations.AddField(
            model_name='dsmv',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dsmv',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Patient'),
        ),
    ]
