# Generated by Django 2.0.2 on 2018-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0002_auto_20180915_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsmv',
            name='d1',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d10',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d11',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d12',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d13',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d14',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d15',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d16',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d17',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d18',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d19',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d20',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d21',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d22',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d23',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d24',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d25',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d3',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d4',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d5',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d6',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d7',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d8',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='dsmv',
            name='d9',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp1',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp10',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp3',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp4',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp5',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp6',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp7',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp8',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart1',
            name='hp9',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp11',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp12',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp13',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp14',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp15',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp16',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp17',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp18',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp19',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp20',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp21',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp22',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp23',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp24',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
        migrations.AlterField(
            model_name='hopkinspart2',
            name='hp25',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=None),
        ),
    ]
