# Generated by Django 2.0.6 on 2018-09-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocPat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField(null=True)),
                ('blood_type', models.CharField(max_length=10, null=True)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('allergies', models.TextField(blank=True, default='', null=True)),
                ('current_medications', models.TextField(blank=True, default='', null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RelativeRelationships',
            fields=[
                ('relationship_num', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='PatientPortal.Patient')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='PatientPortal.Patient')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.RelativeRelationships')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Site'),
        ),
    ]
