# Generated by Django 2.0 on 2018-02-06 19:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('blood_type', models.CharField(max_length=10)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('allergies', models.TextField()),
                ('current_medications', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientPortal.Site'),
        ),
    ]
