# Generated by Django 2.0 on 2018-04-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0002_auto_20180411_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='campsite',
            new_name='site',
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
