# Generated by Django 2.0 on 2018-02-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0003_auto_20180214_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
