# Generated by Django 2.0.2 on 2018-09-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0004_auto_20180923_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', 'Choose one'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=6),
        ),
    ]
