# Generated by Django 3.0.5 on 2020-04-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0005_auto_20180927_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
