# Generated by Django 3.0.5 on 2020-05-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0006_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
