# Generated by Django 3.0.5 on 2020-05-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientPortal', '0007_delete_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatives',
            name='person',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='RelativeRelationships',
        ),
        migrations.DeleteModel(
            name='Relatives',
        ),
    ]
