from django.db import models
from PatientPortal.models import DocPat, Patient, Doctor
from django.core.validators import MaxValueValidator, MinValueValidator


################################################
# TODO: Each of these instances of (ask, identify, etc) should be its own table
#       linked to by Toolkit to allow for inclusion the last time an item was
#       read over (extra metadata) as well as for you to get the history of all
#       the times something has been filled out, and what the responses were,
#       if applicable
################################################

class Toolkit(models.Model):
    def answer_default():
        return False

    docpat = models.ForeignKey(DocPat, on_delete = models.CASCADE) # Not unique Identifier
    ask = models.BooleanField(default=answer_default)
    identify = models.BooleanField(default=answer_default)
    diagnose_and_treat = models.BooleanField(default=answer_default)
    refer = models.BooleanField(default=answer_default)
    reinforce_and_teach = models.BooleanField(default=answer_default)
    recommend = models.BooleanField(default=answer_default)
    reduce_high_risk_behavior = models.BooleanField(default=answer_default)
    be_culturally_attuned = models.BooleanField(default=answer_default)
    prescribe = models.BooleanField(default=answer_default)
    close_and_schedule = models.BooleanField(default=answer_default)
    prevent_burnout = models.BooleanField(default=answer_default)


class HTQ(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    date = models.DateField()
    te1 = models.NullBooleanField()
    te2 = models.NullBooleanField()
    te3 = models.NullBooleanField()
    te4 = models.NullBooleanField()
    te5 = models.NullBooleanField()
    te6 = models.NullBooleanField()
    te7 = models.NullBooleanField()
    te8 = models.NullBooleanField()
    te9 = models.NullBooleanField()
    te10 = models.NullBooleanField()
    te11 = models.NullBooleanField()
    te12 = models.NullBooleanField()
    te13 = models.NullBooleanField()
    te14 = models.NullBooleanField()
    te15 = models.NullBooleanField()
    te16 = models.NullBooleanField()
    te17 = models.NullBooleanField()
    te18 = models.NullBooleanField()
    te19 = models.NullBooleanField()
    te20 = models.NullBooleanField()
    te21 = models.NullBooleanField()
    te22 = models.NullBooleanField()
    te23 = models.NullBooleanField()
    te24 = models.NullBooleanField()
    te25 = models.NullBooleanField()
    te26 = models.NullBooleanField()
    te27 = models.NullBooleanField()
    te28 = models.NullBooleanField()
    te29 = models.NullBooleanField()
    te30 = models.NullBooleanField()
    te31 = models.NullBooleanField()
    te32 = models.NullBooleanField()
    te33 = models.NullBooleanField()
    te34 = models.NullBooleanField()
    te35 = models.NullBooleanField()
    te36 = models.NullBooleanField()
    te37 = models.NullBooleanField()
    te38 = models.NullBooleanField()
    te39 = models.NullBooleanField()
    te40 = models.NullBooleanField()
    te41 = models.TextField(default = '', null=True, blank=True)
   
    pd1 = models.TextField(default = '', null=True, blank=True)
    pd2 = models.TextField(default = '', null=True, blank=True)

    hi1 = models.NullBooleanField()
    hi1_a = models.NullBooleanField()
    hi1_b = models.DurationField(null=True, blank=True)
    hi2 = models.NullBooleanField()
    hi2_a = models.NullBooleanField()
    hi2_b = models.DurationField(null=True, blank=True)
    hi3 = models.NullBooleanField()
    hi3_a = models.NullBooleanField()
    hi3_b = models.DurationField(null=True, blank=True)
    hi4 = models.NullBooleanField()
    hi4_a = models.NullBooleanField()
    hi4_b = models.DurationField(null=True, blank=True)
    hi5 = models.NullBooleanField()
    hi_a = models.DecimalField(max_digits = 4, decimal_places = 1, null=True, blank=True)
    hi_b = models.DecimalField(max_digits = 4, decimal_places = 1, null=True, blank=True)
    hi_c = models.NullBooleanField()


class DSMV(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    date = models.DateField()
    d1 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d2 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d3 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d4 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d5 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d6 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d7 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d8 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d9 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d10 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d11 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d12 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d13 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d14 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d15 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d16 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d17 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d18 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d19 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d20 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d21 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d22 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d23 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d24 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    d25 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    score = models.DecimalField(max_digits = 3, decimal_places = 1)

class TortureHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    date = models.DateField()
    th1 = models.NullBooleanField()
    th2 = models.NullBooleanField()
    th3 = models.NullBooleanField()
    th4 = models.NullBooleanField()
    th5 = models.NullBooleanField()
    th6 = models.NullBooleanField()
    th7 = models.NullBooleanField()
    th8 = models.NullBooleanField()
    th9 = models.NullBooleanField()
    th10 = models.NullBooleanField()
    th11 = models.NullBooleanField()
    th12 = models.NullBooleanField()
    th13 = models.NullBooleanField()
    th14 = models.NullBooleanField()
    th15 = models.NullBooleanField()
    th16 = models.NullBooleanField()
    th17 = models.NullBooleanField()
    th18 = models.NullBooleanField()
    th19 = models.NullBooleanField()
    th20 = models.NullBooleanField()
    th21 = models.NullBooleanField()
    th22 = models.NullBooleanField()
    th23 = models.NullBooleanField()
    th24 = models.NullBooleanField()
    th25 = models.NullBooleanField()
    th26 = models.NullBooleanField()
    th27 = models.NullBooleanField()
    th28 = models.TextField(default = '', null=True, blank=True)

class HopkinsPart1(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    date = models.DateField()
    hp1 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp2 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp3 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp4 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp5 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp6 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp7 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp8 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp9 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp10 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    score = models.DecimalField(max_digits = 3, decimal_places = 1)

class HopkinsPart2(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    date = models.DateField()
    hp11 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp12 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp13 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp14 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp15 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp16 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp17 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp18 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp19 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp20 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp21 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp22 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp23 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp24 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    hp25 = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])
    score = models.DecimalField(max_digits = 3, decimal_places = 1)




        
